name: Sandbox
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  CONAN_PACKAGES_ACCESS_TOKEN: ${{ secrets.CONAN_PACKAGES_ACCESS_TOKEN }}
jobs:
  macos:
    name: macOS (Apple Clang 12)
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/macos-apple-clang
      - name: Download Cache
        uses: ./.github-actions/steps/download-conan-cache
      - name: Build
        uses: ./.github-actions/steps/build
  ubuntu-gcc:
    name: Ubuntu (GCC 9)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/ubuntu-gcc
        with:
          dependencies: libgl-dev
      - name: Download Cache
        uses: ./.github-actions/steps/download-conan-cache
      - name: Build
        uses: ./.github-actions/steps/build
  ubuntu-clang:
    name: Ubuntu (Clang 11)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/ubuntu-clang
        with:
          dependencies: libgl-dev
      - name: Download Cache
        uses: ./.github-actions/steps/download-conan-cache
      - name: Build
        env:
          CC: clang
          CXX: clang++
        uses: ./.github-actions/steps/build
  windows:
    name: Windows (MSVC 16)
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - arch: x86_64
        config:
          - Release
          - Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        uses: ./.github-actions/platforms/windows-msvc
      - name: Download Cache
        uses: ./.github-actions/steps/download-conan-cache
      - name: Build
        uses: ./.github-actions/steps/build
